# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
# python的list对象转换为numpy的array
list_1 = [1,2,3,4]
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [5]:
# 创建二维的array
list_2 = [5,6,7,8]
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# 查看数组的维度
array_2.shape

(2, 4)

In [7]:
# 查看数组元素的个数
array_2.size

8

In [8]:
# 查看数组元素的类型
array_2.dtype

dtype('int32')

In [10]:
# 创建序列array
array_4 = np.arange(1,10)
array_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 创建全零矩阵
array_5 = np.zeros(5)
array_5

array([0., 0., 0., 0., 0.])

In [12]:
# 创建多维的全零矩阵
array_6 = np.zeros((2,3))
array_6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 创建单位矩阵
array_7 = np.eye(5)
array_7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
array_8 = np.eye((3,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [16]:
# 查看返回类型
np.eye(5).dtype

dtype('float64')

In [18]:
np.zeros((2,3)).dtype

dtype('float64')

In [21]:
# 访问数据,下标从0开始，先行后列, 先访问行
array_7[0]

array([1., 0., 0., 0., 0.])

In [22]:
# 访问数据，第一行，第一列
array_7[0][0]

1.0

In [23]:
# 切片
array_7[0:2]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [24]:
array_7[0:2][0:2]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [25]:
array_7[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

# 快速创建array

In [26]:
import numpy as np

In [27]:
# 创建10个随机数，返回一个数组
np.random.randn(10)

array([ 1.74091979,  1.9728176 ,  0.86405551, -0.24160197,  0.43310684,
        1.3795676 ,  1.09581988, -0.69123736,  0.16987935,  0.58862758])

In [28]:
# 创建一个10以内的随机数，重点只返回一个数
np.random.randint(10)

7

In [29]:
# 希望返回的是一个数组，那么，需要指定参数
np.random.randint(10, size=(2,3))

array([[4, 7, 5],
       [6, 4, 5]])

In [31]:
# 重新设置数组
np.random.randint(10, size=10)

array([9, 7, 0, 7, 0, 1, 3, 8, 4, 9])

In [32]:
np.random.randint(10, size=10).reshape(2,5)

array([[4, 4, 4, 2, 4],
       [1, 9, 0, 5, 8]])

In [33]:
# 数组的运算
array_a = np.random.randint(10, size=10).reshape(2,5)
array_a

array([[0, 3, 5, 1, 8],
       [2, 4, 5, 3, 1]])

In [34]:
array_b = np.random.randint(10, size=10).reshape(2,5)
array_b

array([[7, 1, 4, 7, 3],
       [0, 4, 9, 0, 5]])

In [35]:
# 数组的加法
array_a + array_b

array([[ 7,  4,  9,  8, 11],
       [ 2,  8, 14,  3,  6]])

In [36]:
# 数组的减法
array_a - array_b

array([[-7,  2,  1, -6,  5],
       [ 2,  0, -4,  3, -4]])

In [37]:
# 数组的乘法
array_a * array_b

array([[ 0,  3, 20,  7, 24],
       [ 0, 16, 45,  0,  5]])

In [38]:
# 数组的除法
array_a / array_b

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.        , 3.        , 1.25      , 0.14285714, 2.66666667],
       [       inf, 1.        , 0.55555556,        inf, 0.2       ]])

In [45]:
# 矩阵的创建
matricx_c = np.mat([[1,2,3], [4,5,6], [7,8,9],[10,11,12],[13,14,15]])
matricx_c

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [46]:
# 数组转换为矩阵
matricx_b = np.mat(array_b)
matricx_b

matrix([[7, 1, 4, 7, 3],
        [0, 4, 9, 0, 5]])

In [47]:
matricx_a = np.mat(array_a)
matricx_a

matrix([[0, 3, 5, 1, 8],
        [2, 4, 5, 3, 1]])

In [48]:
# 矩阵加法
matricx_a + matricx_b

matrix([[ 7,  4,  9,  8, 11],
        [ 2,  8, 14,  3,  6]])

In [49]:
# 矩阵乘法
matricx_a * matricx_c

matrix([[161, 178, 195],
        [ 96, 111, 126]])

In [50]:
# 矩阵减法
matricx_a - matricx_b

matrix([[-7,  2,  1, -6,  5],
        [ 2,  0, -4,  3, -4]])

# 常用函数

In [52]:
# 查看数组中所有元素的唯一值, 矩阵不能查看唯一值
np.unique(array_a)

array([0, 1, 2, 3, 4, 5, 8])

In [53]:
# 按列进行求和, 最大max，最小min同理
sum(array_a)

array([ 2,  7, 10,  4,  9])

In [54]:
# 按行进行求和, 最大max，最小min同理
sum(array_a[0])

17

In [55]:
# 按列进行求和, 最大max，最小min同理
sum(array_a[:,0])

2

# Array的input和output

In [56]:
import pickle

In [57]:
# 将对应的数组写入到数据文件
with open("array_a.pkl", "wb") as writer:
    pickle.dump(array_a, writer)

In [58]:
! dir array_a.pkl

 驱动器 C 中的卷是 Windows
 卷的序列号是 6682-6B9A

 C:\Users\34927 的目录

2019/11/14  09:57               197 array_a.pkl
               1 个文件            197 字节
               0 个目录 17,354,973,184 可用字节


In [59]:
# 读取数据
with open("array_a.pkl", "rb") as reader:
    temp_array = pickle.load(reader)

In [60]:
temp_array

array([[0, 3, 5, 1, 8],
       [2, 4, 5, 3, 1]])

In [61]:
array_a

array([[0, 3, 5, 1, 8],
       [2, 4, 5, 3, 1]])

In [62]:
# 直接序列化
np.save('array_b', array_b)

In [64]:
!dir array_b*

 驱动器 C 中的卷是 Windows
 卷的序列号是 6682-6B9A

 C:\Users\34927 的目录

2019/11/14  09:59               168 array_b.npy
               1 个文件            168 字节
               0 个目录 17,325,215,744 可用字节


In [65]:
# 直接读取
temp_array_b = np.load("array_b.npy")

In [66]:
temp_array_b

array([[7, 1, 4, 7, 3],
       [0, 4, 9, 0, 5]])

In [67]:
array_b

array([[7, 1, 4, 7, 3],
       [0, 4, 9, 0, 5]])

In [68]:
# 写入多个数组
np.savez("array_ab.npz", array_a=array_a, array_b=array_b)

In [69]:
!dir array_ab.npz

 驱动器 C 中的卷是 Windows
 卷的序列号是 6682-6B9A

 C:\Users\34927 的目录

2019/11/14  10:02               554 array_ab.npz
               1 个文件            554 字节
               0 个目录 17,198,489,600 可用字节


In [70]:
# 读取数据
array_dict = np.load("array_ab.npz")

In [71]:
array_dict

In [72]:
# 通过下标访问
array_dict['array_a']

array([[0, 3, 5, 1, 8],
       [2, 4, 5, 3, 1]])